[versions]
agp = "8.3.2"
ezXHelper = "2.1.0"
kotlin = "1.9.23"
xposed = "82"

[libraries]
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
