[versions]
agp = "8.7.3"
ezXHelper = "2.2.0"
kotlin = "2.0.21"
xposed = "82"

[libraries]
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }